### PR TITLE
Waifu2x

### PR DESCRIPTION
**Pull request by simon300000**
用waifu2x把 from tieba 里面的放大了2倍
参数 --noise_level 2 --scale_ratio 2

### CODE REVIEW

**Comment by ZYFDroid** [comment]
I means there is a tool called Waifu2x that can zoom the image in a lossless way. It can be found on Github.

**Comment by simon300000** [comment]
I did use waifu2x to zoom the images?

**Comment by a-wing** [comment]
What? It would be better to use Travis ci build releases?

**Comment by simon300000** [comment]
Travis ci？I guess it will take like 3 hours to build...

**Comment by simon300000** [comment]
PhotoZoom cost money, but you are right about that.

**Pull request closed without merging**
